# 安全增强版本
version: '3.8'
services:
  web:
    build: .
    ports:
      - "127.0.0.1:8088:8000"  # 只绑定本地，通过Nginx代理
    # ... 其他配置

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # HTTPS支持
    volumes:
      - ./nginx-secure.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # SSL证书目录
    # ... 其他配置